#!/usr/bin/env python3
"""Generate assets/icons/lucide-registry.json from the icons.md concept registry.

Paths are NEVER hand-written. Run after editing the icons.md table:
    npm install lucide-static@<PINNED>    (from /tmp, so it lands in /tmp/node_modules)
    python3 scripts/build_icons.py
Then re-run tools/validate.py and tools/check_icons.py.

2026-08-05: icon family reverted Tabler -> Lucide (rulings: proposals/
2026-08-05-astryx-adoption-rulings.md) — the product and the app-generation
catalog never left Lucide, so the DS spec re-aligns with what ships; a future
family swap is a planned migration. Lucide draws at stroke 2 and the system
down-weights to 1.5 at render — the registry stores paths only. Names are
built from icon-nodes.json (canonical only), so a deprecated alias file
(e.g. history.svg, an alias of rotate-ccw-clock) can never enter the registry.
"""
import re, os, json, sys
PIN = "1.28.0"
PKG = "/tmp/node_modules/lucide-static"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENT_GLYPH = '<path d="M12 5l1.8 5.2L19 12l-5.2 1.8L12 19l-1.8-5.2L5 12l5.2-1.8z" />'

def body(n, nodes):
    """Inner markup from icon-nodes.json (canonical names only)."""
    if n not in nodes: return None
    parts = []
    for tag, attrs in nodes[n]:
        a = " ".join(f'{k}="{v}"' for k, v in attrs.items() if k != "key")
        parts.append(f"<{tag} {a} />")
    return " ".join(parts)

def main():
    nodes = json.load(open(os.path.join(PKG, "icon-nodes.json")))
    md = open(os.path.join(ROOT, "icons.md")).read()
    reg = {}
    for row in re.findall(r"^\|([^|]+)\|([^|]+)\|([^|]*)\|", md, re.M):
        concept = re.sub(r"\s+", " ", re.sub(r"\*", "", row[0])).strip()
        if concept.lower() in ("concept", "---"): continue
        for n in re.findall(r"`([a-z0-9-]+)`", row[1]): reg.setdefault(n, []).append(concept)
    out = {"$source": f"lucide-static@{PIN}", "$stroke": 1.5,
           "$viewBox": "0 0 24 24", "$sizes": [12, 16, 20, 24],
           "$rule": "Generated by scripts/build_icons.py from the icons.md table. Do not hand-edit paths. Lucide CANONICAL names only (icon-nodes.json); deprecated aliases are rejected at build time.",
           "icons": {}}
    missing, aliases = [], []
    for n in sorted(reg):
        b = body(n, nodes)
        if b is None:
            if os.path.exists(os.path.join(PKG, "icons", n + ".svg")): aliases.append(n)
            else: missing.append(n)
            continue
        out["icons"][n] = {"paths": b, "concepts": reg[n]}
    out["icons"]["agent-glyph"] = {"paths": AGENT_GLYPH, "concepts": ["agent"], "custom": True,
        "note": "BRAND-REGISTERED custom path — the sole non-Lucide entry and the sole AI iconography. sparkles/wand/robot are permanently forbidden (icons.md)."}
    dest = os.path.join(ROOT, "assets/icons/lucide-registry.json")
    json.dump(out, open(dest, "w"), indent=1, ensure_ascii=False)
    print(f"wrote {dest} — {len(out['icons'])} icons, {sum(len(v['concepts']) for v in out['icons'].values())} concepts")
    if aliases:
        print(f"ERROR: icons.md uses DEPRECATED Lucide alias names (use canonical): {aliases}", file=sys.stderr); return 1
    if missing:
        print(f"ERROR: icons.md names with no Lucide icon: {missing}", file=sys.stderr); return 1
    return 0

if __name__ == "__main__": sys.exit(main())
