#!/usr/bin/env python3
"""Generate assets/icons/tabler-registry.json from the icons.md concept registry.

Paths are NEVER hand-written. Run after editing the icons.md table:
    npm install @tabler/icons@<PINNED>
    python3 scripts/build_icons.py
Then re-run tools/validate.py.
"""
import re, os, json, sys
PIN = "3.31.0"
TD  = f"/tmp/node_modules/@tabler/icons/icons/outline"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENT_GLYPH = '<path d="M12 5l1.8 5.2L19 12l-5.2 1.8L12 19l-1.8-5.2L5 12l5.2-1.8z" />'

def body(n):
    p = os.path.join(TD, n + ".svg")
    if not os.path.exists(p): return None
    b = re.search(r"<svg[^>]*>(.*)</svg>", open(p).read(), re.S).group(1)
    return re.sub(r"\s+", " ", re.sub(r'<path stroke="none"[^/]*/>', "", b)).strip()

def main():
    md = open(os.path.join(ROOT, "icons.md")).read()
    reg = {}
    for row in re.findall(r"^\|([^|]+)\|([^|]+)\|([^|]*)\|", md, re.M):
        concept = re.sub(r"\s+", " ", re.sub(r"\*", "", row[0])).strip()
        if concept.lower() in ("concept", "---"): continue
        for n in re.findall(r"`([a-z0-9-]+)`", row[1]): reg.setdefault(n, []).append(concept)
    out = {"$source": f"@tabler/icons@{PIN} — outline set", "$stroke": 1.5,
           "$viewBox": "0 0 24 24", "$sizes": [12, 16, 20, 24],
           "$rule": "Generated by scripts/build_icons.py from the icons.md table. Do not hand-edit paths.",
           "icons": {}}
    missing = []
    for n in sorted(reg):
        b = body(n)
        if b is None: missing.append(n); continue
        out["icons"][n] = {"paths": b, "concepts": reg[n]}
    out["icons"]["agent-glyph"] = {"paths": AGENT_GLYPH, "concepts": ["agent"], "custom": True,
        "note": "BRAND-REGISTERED custom path — the sole non-Tabler entry and the sole AI iconography. sparkles/wand/robot are permanently forbidden (icons.md)."}
    dest = os.path.join(ROOT, "assets/icons/tabler-registry.json")
    json.dump(out, open(dest, "w"), indent=1, ensure_ascii=False)
    print(f"wrote {dest} — {len(out['icons'])} icons, {sum(len(v['concepts']) for v in out['icons'].values())} concepts")
    if missing:
        print(f"ERROR: icons.md names with no Tabler file: {missing}", file=sys.stderr); return 1
    return 0

if __name__ == "__main__": sys.exit(main())
